### PR TITLE
Fix ordering of competitions on group page

### LINKED ISSUE #796: Ordering of finished competitions on Group page to be newest-oldest
Finished competitions on Group page should be ordered with the most recent at the top, going down to the oldest.
Currently it's oldest -> newest.
It should continue to prioritise and order ongoing and upcoming competitions as it seems to already.

image

### PR DESCRIPTION
**Pull request by mauwaz**
Fix #796 

Fix ordering of `ongoing` and `finished` competitions on group page.
- Ongoing competitions that ends first are displayed first
- Finished competitions that ends later are displayed first

**Screenshots**
Screenshot  Finished  Sort

Screenshot  Ongoing  Sort

### CODE REVIEW

File: app/src/pages/Group/containers/CompetitionsTable.jsx [hunk 1]
```diff
@@ -74,6 +74,14 @@ function sortCompetitions(competitions) {
   if (!competitions) return [];
 
   return competitions.sort((a, b) => {
+    if (a.status === b.status) {
```
Comment (Jonxslays) [inline app/src/pages/Group/containers/CompetitionsTable.jsx:77]: This is the same condition being checked on line 86, so if the code passes that comparison it means that the status are guaranteed to be the same because subtracting the indices will result in a falsy 0 value.

I think it would be better to not perform the status comparison twice.
Did you try to fit these changes into the below return block?

Here's something I came up with if you're looking for inspiration:
image

**Comment by psikoi** [comment]
beautiful, merging!

thanks @mauwaz for the contribution, and @Jonxslays for the review
